server:
  port: 8989
  servlet:
    context-path: /springboot_day2
    jsp:
      init-parameters:
        development: true  #开启jsp页面的开发模式 作用：修改jsp页面无需重启springboot应用

#声明基本属性注入值
name: xiaochen
age: 23
price: 23.23
birthday: 2020/12/12 12:12:12 #注意：默认的日期格式为 yyyy/mm/dd HH:MM:SS
sex: true
qqs: 8080,6767,2323 #注入数组的时候，多个元素用 “,” 逗号隔开
lists: xiaohu,xiaochen,xiaowang,xiaohei #注入list时候，多个元素用 “,” 逗号隔开 和数组一样
maps: "{'aa':'销户','bb':'小王'}" #注入map集合可以使用 json形式进行注入 注意:使用@Value注入时必须加入 #{${属性}}

#声明对象方式注入
orders:
  id: 20
  name: xiaoming
  price: 23.23

#配置jsp视图前缀和后后缀  解析结果： 前缀 + controller返回值 + 后缀
spring:
  mvc:
    view:
      prefix: /   #视图前缀
      suffix: .jsp  #视图后缀
